dataset:
  type: PascalVOCDataset
  data_dir: ./data/voc07+12
  size: &size [512, 512]
  encoder:
    type: RetinaEncoder
    input_size: *size
  loader:
    batch_size: 16
    num_workers: 2

model:
  type: EfficientDet
  size: d0
  backbone:
    frozen_stages: 2
  input_size: *size

optimizer:
  type: SGD
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  type: MultiStepLR
  milestones: [40, 60]
  gamma: 0.1
  warmup_epochs: 3
  warmup_ratio: 0.1

metric:
  anno_path: ./data/voc07+12/annotations/instances_val.json
  pred_size: *size

runtime:
  epochs: 75
